name: flutter_yim
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 请尽量使用最新版本 通过 https://pub.dev/ 查看
  # https://github.com/alibaba/flutter_boost
  flutter_boost: ^0.0.411

  # module_wx & module_novel
  # https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # https://github.com/dart-lang/web_socket_channel
  web_socket_channel: ^1.0.12
  # https://github.com/flutter/plugins
  webview_flutter: ^0.3.7+1
  # https://github.com/flutter/plugins
  image_picker: ^0.6.0+3
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^0.8.0
  # https://github.com/serenader2014/flutter_carousel_slider
  carousel_slider: ^1.3.0
  # https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.0.4
  # https://github.com/dart-lang/intl
  intl: ^0.15.8

  # module_cloud_music
  # https://github.com/dart-lang/json_serializable
  json_annotation: ^2.3.0
  # https://github.com/flutter/plugins
  shared_preferences: ^0.5.2
  # https://github.com/marcojakob/dart-event-bus
  event_bus: ^1.1.0
  # https://github.com/brianegan/flutter_redux
  flutter_redux: ^0.5.3
  # https://github.com/flutterchina/dio
  dio: ^2.1.3
  # https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^3.1.0
  # https://github.com/luanpotter/audioplayers
  audioplayers: ^0.10.1

  # module_douban
  # https://github.com/flutter/plugins
  share: ^0.6.1+1
  # https://github.com/dart-lang/http
  http: ^0.12.0+2
  # https://github.com/dart-lang/html
  html: ^0.14.0+2
  # https://github.com/flutter/packages
  palette_generator: ^0.1.1
  # https://github.com/renancaraujo/photo_view
  photo_view: ^0.3.3
  # https://github.com/brianegan/chewie
  chewie: ^0.9.7
  # https://github.com/flutter/plugins
  video_player: ^0.10.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # module_wx
  - assets/mod_wx/
  - assets/mod_wx/wx7/
  - assets/mod_wx/wx_mock.json
  - assets/mod_wx/avatars/
  # module_novel
  - assets/mod_novel/mock/
  - assets/mod_novel/img/
  # module_cloud_music
  - assets/mod_cloud_music/img/
  # module_douban
  - assets/mod_douban/img/

  fonts:
  - family: appiconFonts
    fonts:
      - asset: assets/mod_wx/iconfont.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
